# Generated by Django 4.2 on 2025-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateprofile',
            name='bar_council_number',
        ),
        migrations.AddField(
            model_name='user',
            name='bar_council_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
